/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainPagesRouteImport } from './routes/main-pages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainPagesCategoriesRouteImport } from './routes/main-pages.categories'
import { Route as MainPagesCalculationRouteImport } from './routes/main-pages.calculation'

const MainPagesRoute = MainPagesRouteImport.update({
  id: '/main-pages',
  path: '/main-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainPagesCategoriesRoute = MainPagesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainPagesRoute,
} as any)
const MainPagesCalculationRoute = MainPagesCalculationRouteImport.update({
  id: '/calculation',
  path: '/calculation',
  getParentRoute: () => MainPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main-pages': typeof MainPagesRouteWithChildren
  '/main-pages/calculation': typeof MainPagesCalculationRoute
  '/main-pages/categories': typeof MainPagesCategoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main-pages': typeof MainPagesRouteWithChildren
  '/main-pages/calculation': typeof MainPagesCalculationRoute
  '/main-pages/categories': typeof MainPagesCategoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main-pages': typeof MainPagesRouteWithChildren
  '/main-pages/calculation': typeof MainPagesCalculationRoute
  '/main-pages/categories': typeof MainPagesCategoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/main-pages' | '/main-pages/calculation' | '/main-pages/categories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/main-pages' | '/main-pages/calculation' | '/main-pages/categories'
  id:
    | '__root__'
    | '/'
    | '/main-pages'
    | '/main-pages/calculation'
    | '/main-pages/categories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainPagesRoute: typeof MainPagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main-pages': {
      id: '/main-pages'
      path: '/main-pages'
      fullPath: '/main-pages'
      preLoaderRoute: typeof MainPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main-pages/categories': {
      id: '/main-pages/categories'
      path: '/categories'
      fullPath: '/main-pages/categories'
      preLoaderRoute: typeof MainPagesCategoriesRouteImport
      parentRoute: typeof MainPagesRoute
    }
    '/main-pages/calculation': {
      id: '/main-pages/calculation'
      path: '/calculation'
      fullPath: '/main-pages/calculation'
      preLoaderRoute: typeof MainPagesCalculationRouteImport
      parentRoute: typeof MainPagesRoute
    }
  }
}

interface MainPagesRouteChildren {
  MainPagesCalculationRoute: typeof MainPagesCalculationRoute
  MainPagesCategoriesRoute: typeof MainPagesCategoriesRoute
}

const MainPagesRouteChildren: MainPagesRouteChildren = {
  MainPagesCalculationRoute: MainPagesCalculationRoute,
  MainPagesCategoriesRoute: MainPagesCategoriesRoute,
}

const MainPagesRouteWithChildren = MainPagesRoute._addFileChildren(
  MainPagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainPagesRoute: MainPagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
